### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by JueXiuHuang** [ldslds449/Dice_War_Bot#5]
- [ ] Task-23 Setting UI
- [ ] Task-10 太陽升級時需要將 SolarX 移出隊伍
- [ ] Task-14 HDR++++++
- [ ] Task-15 新增README.md
- [ ] Task-9 自動校準中心點
- [ ] Task-23 鑰匙數量
- [ ] FutureWork Linear Regression for action optimization
- [x] Task-7 單人勝利的詳細資訊可能會讓 bot 卡住
- [x] FutureWork  Reinforcement Learning for action optimization
- [x] Task-22 未知情況下Bot會卡住
- [x] Task-21 在未知情況下會跳出截圖錯誤
- [x] Task-20 遊戲卡住時Bot會跟者卡住
- [x] Task-17 七星骰子辨識問題
- [x] Task-16 把 autoplay 與 restart app 設定成預設值
- [x] Task-13 優化 Action
- [x] Task-12 新增 requirements.txt
- [x] Task-11 戰鬥統計 bug
- [x] #6
- [x] Task-6 小丑合成機制優化 A (Stage 4 之後 strictOrderMerge() 低於 dice_level 的 order 變為整個隊伍)
- [x] Task-5 Bot 循環卡住 (有偵測到 lobby 但不會尋找對戰)
- [x] Task-4 小丑星數判斷
- [x] Task-3 複製過的成長星數判斷
- [x] Task-2 勝敗場統計 (計算掛機期間勝敗場數量)
- [x] Task-1 Add ADB_USB and ADB_TCP modes
